// Static (prerendered) routes: legal and info pages, one page per dataset document, size pages and
// the print guide, in English and in every translated locale (src/i18n). STUDIO's App calls
// matchStaticRoute(pathname); scripts/prerender.ts walks staticRoutes() and routeMeta().
import type { ReactElement } from "react";
import { DOCUMENTS, type DocumentSpec } from "../core/documents";
import { LEGAL_UPDATED, REPO_URL, SITE_NAME, SITE_URL } from "../config";
import {
  DEFAULT_LOCALE,
  LOCALES,
  alternatesFor,
  isTranslatable,
  localeOf,
  toEnglishPath,
  withLocale,
  type Locale,
} from "../i18n";
import { localizeDocument } from "../i18n/localize";
import { loadedTranslations } from "../i18n/registry";
import { strings } from "../i18n/strings";
import { DocumentPage } from "./pages/DocumentPage";
import { DocumentsIndexPage } from "./pages/DocumentsIndex";
import { AboutPage, SupportPage } from "./pages/Info";
import { AccessibilityPage, PrivacyPage, TermsPage } from "./pages/Legal";
import { sizePages, type PageDef } from "./pages/SizePages";
import { checkedIso, documentFaq, documentMeta, docPath, latestCheck, type Faq } from "./pages/content";

export interface HreflangLink {
  hreflang: string;
  /** Absolute URL. */
  href: string;
}
export interface RouteMeta {
  title: string;
  description: string;
  canonical: string;
  jsonLd?: object[];
  /** Keep the page out of search results (thin or utility pages). It is also left out of the sitemap. */
  noindex?: boolean;
  /** YYYY-MM-DD: when the page's content last changed (the dataset check date, or the legal update). */
  lastmod?: string;
  /** Absolute URL of the social card, and its alt text. */
  ogImage: string;
  ogImageAlt: string;
  /** <html lang>, and og:locale. */
  lang: string;
  dir: "ltr" | "rtl";
  ogLocale: string;
  /** hreflang alternates (including x-default) for pages that exist in more than one language. */
  alternates: HreflangLink[];
}
export interface StaticRoute extends RouteMeta {
  element: ReactElement;
}

const HOME_META = {
  title: "PortraitPass — Free passport photo maker, sized exactly",
  description:
    "Free passport and ID photo maker that runs in your browser. Exact sizes, head and eye guides, and print sheets. Nothing is uploaded, no watermark, no account.",
};
const STUDIO_META = {
  title: "Passport photo studio — PortraitPass",
  description:
    "Frame, check and export a passport, visa or ID photo in your browser. Head and eye guides, exact sizes and print sheets. Your photo never leaves your device.",
};

export function normalizePath(pathname: string): string {
  let p = pathname.split(/[?#]/)[0] || "/";
  if (!p.startsWith("/")) p = `/${p}`;
  return p === "/" ? "/" : `${p.replace(/\/+$/, "")}/`;
}

const absolute = (path: string) => `${SITE_URL}${path}`;
const ORG_ID = `${SITE_URL}/#organization`;
const SITE_ID = `${SITE_URL}/#website`;

// ------------------------------------------------------------ social cards
const DOC_PATH_ID = new Map(DOCUMENTS.map((d) => [`/${d.id}-photo/`, d.id]));
/**
 * The card for a page: one per document and per size or guide page (generated by the prerender
 * script from scripts/lib/og-cards.ts), shared by every language. Other pages use the home card.
 */
function ogImageFor(path: string): string {
  const en = toEnglishPath(path);
  if (!isTranslatable(en)) return absolute("/og.png");
  return absolute(`/og/${DOC_PATH_ID.get(en) ?? en.replace(/\//g, "")}.png`);
}
const withCommon = (path: string, meta: Omit<RouteMeta, "ogImage" | "ogImageAlt"> & { ogImageAlt?: string }): RouteMeta => ({
  ...meta,
  ogImage: ogImageFor(path),
  ogImageAlt: meta.ogImageAlt ?? meta.title,
});

// ------------------------------------------------------------ structured data
const ALL_CHECKED = () => latestCheck(DOCUMENTS);
/** Who publishes the site. Only facts that are on the site: no ratings, no invented people. */
const organizationLd = () => ({
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": ORG_ID,
  name: SITE_NAME,
  url: absolute("/"),
  logo: { "@type": "ImageObject", url: absolute("/icons/icon-512.png"), width: 512, height: 512 },
  description:
    "An independent open-source project that sizes and frames passport, visa and ID photos in the browser. Not affiliated with any government.",
  sameAs: [REPO_URL],
});
const websiteLd = () => ({
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": SITE_ID,
  url: absolute("/"),
  name: SITE_NAME,
  alternateName: ["PortraitPass passport photo maker"],
  description: HOME_META.description,
  inLanguage: "en",
  publisher: { "@id": ORG_ID },
});
const applicationLd = () => ({
  "@context": "https://schema.org",
  "@type": "WebApplication",
  "@id": `${SITE_URL}/#app`,
  name: SITE_NAME,
  url: absolute("/"),
  description: HOME_META.description,
  applicationCategory: "MultimediaApplication",
  applicationSubCategory: "Passport and ID photo maker",
  operatingSystem: "Any",
  browserRequirements: "Requires JavaScript and a current web browser.",
  isAccessibleForFree: true,
  license: "https://opensource.org/license/mit",
  image: absolute("/og.png"),
  featureList: [
    "Exact photo sizes for 49 passports, visas and ID documents, each with its source",
    "Head and eye position guides and live measurements",
    "Print sheets on 4x6, A4 and Letter paper",
    "Exact pixel and file size export for upload forms",
    "Runs in the browser; the photo is never uploaded",
  ],
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  publisher: { "@id": ORG_ID },
});
/** The page itself: language, last check date and, where the numbers come from, its sources. */
function webPageLd(opts: {
  path: string;
  title: string;
  description: string;
  lang: string;
  lastmod?: string;
  sources?: { title: string; url: string }[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${absolute(opts.path)}#webpage`,
    url: absolute(opts.path),
    name: opts.title,
    description: opts.description,
    inLanguage: opts.lang,
    isPartOf: { "@id": SITE_ID },
    publisher: { "@id": ORG_ID },
    primaryImageOfPage: { "@type": "ImageObject", url: ogImageFor(opts.path), width: 1200, height: 630 },
    ...(opts.lastmod ? { dateModified: opts.lastmod, lastReviewed: opts.lastmod } : {}),
    ...(opts.sources?.length
      ? { isBasedOn: opts.sources.map((s) => ({ "@type": "CreativeWork", name: s.title, url: s.url })) }
      : {}),
  };
}
/** The dataset behind the pages, for Google Dataset Search. The JSON file is written by scripts/prerender.ts. */
function datasetLd() {
  const countries = [...new Set(DOCUMENTS.map((d) => d.country))].sort();
  const checks = DOCUMENTS.flatMap((d) => d.sources.map((s) => s.checkedAt)).sort();
  const sources = [...new Set(DOCUMENTS.flatMap((d) => d.sources.map((s) => s.url)))].sort();
  return {
    "@context": "https://schema.org",
    "@type": "Dataset",
    "@id": `${SITE_URL}/#dataset`,
    name: "Passport, visa and ID photo requirements",
    description: `Photo size, head and eye position, background and file size rules for ${DOCUMENTS.length} passports, visas and ID documents from ${countries.length} countries and regions. Each entry lists the issuing authority's own source page and the date it was last checked. The entries are a well-sourced starting point: re-check the source page before relying on a number.`,
    url: absolute("/documents/"),
    keywords: ["passport photo size", "visa photo requirements", "ID photo dimensions", "photo file size limit", "head height", "biometric photo"],
    license: "https://opensource.org/license/mit",
    isAccessibleForFree: true,
    inLanguage: "en",
    creator: { "@id": ORG_ID },
    publisher: { "@id": ORG_ID },
    dateModified: checks[checks.length - 1],
    temporalCoverage: `${checks[0]}/${checks[checks.length - 1]}`,
    spatialCoverage: countries.map((c) => ({ "@type": "Place", name: c })),
    variableMeasured: [
      "Printed photo width and height (mm)",
      "Head height range (mm)",
      "Eye line position (mm)",
      "Background colour",
      "Upload width and height (px)",
      "File size limit (KB)",
      "Accepted file formats",
    ],
    isBasedOn: sources,
    distribution: [
      { "@type": "DataDownload", encodingFormat: "application/json", contentUrl: absolute("/data/documents.json") },
    ],
    sameAs: `${REPO_URL}/tree/main/src/core/data`,
  };
}

function faqLd(faq: Faq[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faq.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };
}
function crumbLd(items: { name: string; path?: string }[], L: Locale) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [{ name: strings(L).shell.home, path: "/" }, ...items].map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      ...(it.path ? { item: absolute(it.path) } : {}),
    })),
  };
}

/** Language, direction and hreflang alternates for a page at `path`. */
function localeMeta(path: string) {
  const L = localeOf(path);
  const alts = alternatesFor(path);
  const alternates: HreflangLink[] = alts.length
    ? [
        ...alts.map((a) => ({ hreflang: a.hreflang, href: absolute(a.path) })),
        {
          hreflang: "x-default",
          href: absolute(alts.find((a) => a.locale === DEFAULT_LOCALE)!.path),
        },
      ]
    : [];
  return {
    lang: LOCALES[L].hreflang,
    dir: LOCALES[L].dir,
    ogLocale: LOCALES[L].ogLocale,
    alternates,
  };
}

interface Entry {
  path: string;
  build: () => StaticRoute;
}

const fixed = (
  path: string,
  title: string,
  description: string,
  crumb: string,
  element: () => ReactElement,
  opts: { noindex?: boolean } = {},
): Entry => ({
  path,
  build: () => ({
    ...withCommon(path, {
      title,
      description,
      canonical: absolute(path),
      jsonLd: [crumbLd([{ name: crumb }], DEFAULT_LOCALE)],
      lastmod: LEGAL_UPDATED,
      ...(opts.noindex ? { noindex: true } : {}),
      ...localeMeta(path),
    }),
    element: element(),
  }),
});

function fromDef(def: PageDef, L: Locale): Entry {
  const path = withLocale(def.path, L);
  return {
    path,
    build: () => {
      const meta = localeMeta(path);
      const lastmod = ALL_CHECKED();
      return {
        ...withCommon(path, {
          title: def.title,
          description: def.description,
          canonical: absolute(path),
          lastmod,
          jsonLd: [
            crumbLd([{ name: def.crumb }], L),
            webPageLd({ path, title: def.title, description: def.description, lang: meta.lang, lastmod }),
            ...(def.faq ? [faqLd(def.faq)] : []),
          ],
          ...meta,
        }),
        element: def.element,
      };
    },
  };
}

function fromDocument(doc: DocumentSpec, L: Locale): Entry {
  const path = docPath(doc, L);
  return {
    path,
    build: () => {
      const { title, description } = documentMeta(doc, L);
      const meta = localeMeta(path);
      const lastmod = checkedIso(doc) || undefined;
      return {
        ...withCommon(path, {
          title,
          description,
          canonical: absolute(path),
          lastmod,
          jsonLd: [
            crumbLd(
              [
                { name: strings(L).index.crumb, path: withLocale("/documents/", L) },
                { name: localizeDocument(doc, L).name },
              ],
              L,
            ),
            webPageLd({
              path,
              title,
              description,
              lang: meta.lang,
              lastmod,
              sources: doc.sources.map((x) => ({ title: x.title, url: x.url })),
            }),
            faqLd(documentFaq(doc, L)),
          ],
          ...meta,
        }),
        element: <DocumentPage doc={doc} locale={L} />,
      };
    },
  };
}

function documentsIndex(L: Locale): Entry {
  const path = withLocale("/documents/", L);
  const t = strings(L);
  return {
    path,
    build: () => {
      const meta = localeMeta(path);
      const title = t.meta.indexTitle;
      const description = t.meta.indexDescription(DOCUMENTS.length);
      const lastmod = ALL_CHECKED();
      return {
        ...withCommon(path, {
          title,
          description,
          canonical: absolute(path),
          lastmod,
          jsonLd: [
            crumbLd([{ name: t.index.crumb }], L),
            webPageLd({ path, title, description, lang: meta.lang, lastmod }),
            // The dataset is described once, on the English page (its JSON file is English).
            ...(L === DEFAULT_LOCALE ? [datasetLd()] : []),
          ],
          ...meta,
        }),
        element: <DocumentsIndexPage locale={L} />,
      };
    },
  };
}

/** Documents, size pages and print guide in one locale. */
function localizedEntries(L: Locale): Entry[] {
  const list: Entry[] = [documentsIndex(L), ...sizePages(L).map((d) => fromDef(d, L))];
  const taken = new Set(list.map((e) => e.path));
  for (const doc of DOCUMENTS) {
    const path = docPath(doc, L);
    if (taken.has(path)) continue;
    taken.add(path);
    list.push(fromDocument(doc, L));
  }
  return list;
}

// Translated pages exist only for language packs that are loaded (a page load needs one language;
// the prerender script loads them all), so the table is rebuilt if the set of loaded packs changes.
let cache: Map<string, Entry> | undefined;
let cacheKey = "";
function entries(): Map<string, Entry> {
  const translations = loadedTranslations();
  const key = translations.join();
  if (cache && key === cacheKey) return cache;
  const list: Entry[] = [
    fixed(
      "/about/",
      "About PortraitPass",
      "An independent open-source passport photo tool. Your photos stay on your device. Learn how it works, where the numbers come from and what it cannot promise.",
      "About",
      () => <AboutPage />,
    ),
    fixed(
      "/support/",
      "Support PortraitPass",
      "Tips keep PortraitPass free, private and open source. Optional one-time or monthly tips; they never unlock features or touch your photos.",
      "Support",
      () => <SupportPage />,
      // A short tipping page: nothing to rank for, so it stays out of search results.
      { noindex: true },
    ),
    fixed(
      "/privacy/",
      "Privacy — PortraitPass",
      "Your photo never leaves your device. What the host logs, why there are no cookies or analytics, and what a saved project file contains.",
      "Privacy",
      () => <PrivacyPage />,
    ),
    fixed(
      "/terms/",
      "Terms — PortraitPass",
      "PortraitPass is a free open-source tool provided as is, under the MIT License, with no guarantee that any photo is accepted.",
      "Terms",
      () => <TermsPage />,
    ),
    fixed(
      "/accessibility/",
      "Accessibility — PortraitPass",
      "How PortraitPass works with a keyboard and screen reader, the WCAG 2.2 AA standard we aim for, known limits, and how to report an accessibility barrier.",
      "Accessibility",
      () => <AccessibilityPage />,
    ),
    // English documents index (its title text lives with the other English strings).
    documentsIndex(DEFAULT_LOCALE),
    ...sizePages(DEFAULT_LOCALE).map((d) => fromDef(d, DEFAULT_LOCALE)),
  ];
  const taken = new Set(list.map((e) => e.path));
  // The US and UK passport pages double as the long-standing keyword URLs.
  for (const doc of DOCUMENTS) {
    const path = docPath(doc);
    if (taken.has(path)) continue;
    taken.add(path);
    list.push(fromDocument(doc, DEFAULT_LOCALE));
  }
  for (const L of translations) list.push(...localizedEntries(L));
  cacheKey = key;
  cache = new Map(list.map((e) => [e.path, e]));
  return cache;
}

/** Route for a pathname, or undefined (home, studio, and unknown paths belong to the app). */
export function matchStaticRoute(pathname: string): StaticRoute | undefined {
  return entries().get(normalizePath(pathname))?.build();
}

/** Every path to prerender and list in the sitemap, in a stable order. */
export function staticRoutes(): string[] {
  return ["/", "/studio/", ...entries().keys()];
}

/** Title, description and structured data for any prerendered path (including / and /studio/). */
export function routeMeta(pathname: string): RouteMeta | undefined {
  const path = normalizePath(pathname);
  const base = localeMeta(path);
  if (path === "/")
    return withCommon(path, {
      ...HOME_META,
      ...base,
      canonical: absolute("/"),
      lastmod: ALL_CHECKED(),
      jsonLd: [organizationLd(), websiteLd(), applicationLd()],
    });
  // The studio is the app itself: an empty shell until the script runs, with the same address for
  // every document (?doc=). The document pages and the home page are what should rank, so it is
  // kept out of the index (links from it are still followed).
  if (path === "/studio/")
    return withCommon(path, { ...STUDIO_META, ...base, canonical: absolute("/studio/"), noindex: true });
  const route = matchStaticRoute(path);
  if (!route) return undefined;
  const { element: _element, ...meta } = route;
  return meta;
}
